_layouts/review.html, _posts/2017-01-27-welcome-to-vital-literature-review.markdown, about.md, how-to-install-ruby.md
Added two files:
* How to add a review
* How to install Ruby (for previewing the site locally)
=> Add How to add a review

how-to-install-ruby.md
=> Fix the link to redirect to the 'Previewing your post locally' id.

course/_posts/2017-01-27-cs231n-convolutional-neural-networks-visual-recognition.md
Replace tag `convolutional-networks` with `CNN`
See issue: https://github.com/vitalab/vitalab.github.io/issues/10
=> Change tag to CNN

deep-learning/_posts/2017-02-28-surveyMedicalImageAnalysis.md
=> Survey of deep learning methods applied to medical image analysis

js/search.js, search.html
* Enable search by paper author and venue
* Disable search by content
=> Enable search by paper author and venue

_includes/head.html, assets/custom.css, how-to.md
* Added some custom css for tables so they are readable.
* Make the tags on how-to page a table.
=> Fix table css

deep-learning/_posts/2017-03-31-deconv.md
Last fixes from @jodoin comments.
=> Fix typo in conv-deconv.

deep-learning/_posts/2018-11-23-OBELISK.md, deep-learning/_posts/2018-11-30-NeuroNet.md, deep-learning/_posts/2018-12-21-DeepTract.md, deep-learning/_posts/2019-01-24-NeuroanatomyDeepMultiStructuralShapeAnalysis.md
Fix cross-references:
- Use numbered anchors.
- Indent each reference's paragraph so that it is displayed correctly.
Minor fixes to some references (e.g. link to public repository review,
fix links, increase consistency across references).
=> BUG: Fix cross-references.

CONTRIBUTING.md, README.md
Improve the `README.md` file contents:
- Add a short explanation (a longer one is available in the public web
home page) about the purpose of the repository.
- Link to a `CONTRIBUTING.md` file where contributing guideline
documentation is linked.
=> ENH: Improve the `README.md` file contents.

how-to-install-ruby.md
Remove latest Ruby version installation notice, as discussed in #317.
=> DOC: Remove latest Ruby version installation notice.

2019-05-07-gan-open-problems.md
=> GAN Open problems

utils/refactor_categories.sh
Fix the script's location in the repository without assuming a
particular name for the latter.
=> BUG: Fix the script's location in the repository

article/_posts/2019-05-30-DistortionCorrectionSynthesizedB0.md
Add synthesized B0 diffusion distortion correction paper review.
=> ENH: Add synthesized B0 diffusion distortion correction paper review

article/_posts/2019-03-21-JointLearningBrainSegmentationHeterogeneousData.md
Cross-reference article to public site URL.
=> ENH: Cross-reference article to public site URL

utils/check_tags.sh
Improve displayed message in tag check script.
=> DOC: Improve displayed message in tag check script

utils/hooks/pre-commit
Fix file inclusion pattern in pre-commit hook.
=> BUG: Fix file inclusion pattern in pre-commit hook

article/_posts/2019-06-13-DeepBundle.md
Fix DeepBundle paper review tag.
=> BUG: Fix DeepBundle paper review tag

_layouts/review.html
I added a border, some padding and margin to the images. I think it makes the posts easier to read.
=> Improve layout of images

utils/check_cross_ref_images.sh
Improve cross-reference check script:
- Improve variable naming.
- Use the non-existing cross-reference file count as the condition to
report the errors.
=> ENH: Improve cross-reference check script

utils/check_png_images.sh, utils/hooks/pre-commit
Add script to check PNG cross-ref file existence to pre-commit hook.
=> ENH: Add script to check PNG cross-ref file existence

.travis.yml, utils/hooks/pre-commit
* Change `pre-commit` hook so that it executes on all changes in the current branch relative to `master` (instead of executing on uncommitted changes)
* Add Travis CI config that runs `pre-commit`
=> Add CI check for using pre-commit hook

article/_posts/2020-02-13-CSVAE.md
- Replaced unrecognized "\dots" in LaTeX
=> Fixed broken LaTeX in CSVAE (again)

article/_posts/2020-02-13-CSVAE.md
I finally setup a local environment for jekyll that allowed me to debug the last bits of the LaTeX-heavy review I made whose display was completely broken in jekyll :'(
=> Fixed LaTeX incompatible with jekyll

README.md
Add the Travis CI badge to the `README` file.
=> ENH: Add the Travis CI badge to the `README` file

article/_posts/2020-08-13-DisentanglingByFactorising.md
Title is self explanatory :wink:
=> Fixed capitalization in equation from "Disentangling by Factorising" review

blog/_posts/2021-02-19-selfsupervised-learning.md
Want to know more about self-supervised learning?  Checkout these blog posts!
=> Self-supervised learning

_data/publications.yml, publications.html
Pas obligé de mettre tous les tags s'ils ne sont pas pertinents (doi, pages, journal, etc.)
=> ENH: Publications

_includes/header.html, categories.html, how-to.md, members.html, publications.html, recent.html, search.html, webinar.html
Remove "how-to" from the menu and order pages
=> ENH: Menu ordering

article/_posts/2021-07-02-Modelling3dBrainMriUsing2dVae.md
Improved explanation of Gaussian model for sampling across slices in the latent space.
=> Improved review of 3D brain MRI modelling using 2D VAE

article/_posts/2021-07-09-SigmaVAE.md
Fix sigma-VAE paper review math expression.
=> ENH: Fix sigma-VAE paper review math expression

article/_posts/2019-05-15-contrastiveLoss.md
When reading about contrastive loss, I was confused by the concept of similarity. I think it's important to describe what we mean by similarity, and how it is determined concretely.
=> Add details in contrastive loss review

_data/tags.yml, _layouts/document.html, categories.html, tutorial/_posts/2024-12-04-diffusionNetworks.md
- I uploaded the diffusion networks pdf under the tutorials.
- I made a custom template to have a beautiful button to view the PDF and a line that writes when the document was last updated (so I can eventually update the slides with the comments I received).
- While I was there, I changed the "Categories" section to show the drop-down menus with arrows instead of checkboxes (I can revert the change if you preferred checkboxes).
=> Diffusion document, categories visual update, new document template

tutorial/_posts/2024-12-17-INR.md
=> FIX: github2colab link in INR tutorial
